version: '3'

services:
  database:
    networks:
      - default
    image: postgres:14-alpine
    container_name: db.uptobox-publisher
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app_local
      - POSTGRES_DB=app
      - PGDATA=/var/lib/postgresql/data

  python:
    networks:
      - default
    container_name: python.uptobox-publisher
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    entrypoint:
      - python
    volumes:
      - .:/app
      - .cache:/root/.cache
    env_file:
      - .env

  web:
    networks:
      - default
      - traefik
    depends_on:
      - database
    container_name: web.uptobox-publisher
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.services.web_uptobox_publisher.loadbalancer.server.port=80
      - traefik.http.routers.web_uptobox_publisher.tls=true
      - traefik.http.routers.web_uptobox_publisher.tls.certResolver=patiashvili
      - traefik.http.routers.web_uptobox_publisher.rule=Host(`uptobox.patiashvili`)


volumes:
  database-data:

networks:
  default:
    driver: bridge
  traefik:
    name: traefik_proxy