STATUS_CODE_OK = 200
STATUS_CODE_NO_CONTENT = 204

STATUS_CODE_BAD_REQUEST = 400
STATUS_CODE_UNAUTHORIZED = 401
STATUS_CODE_FORBIDDEN = 403
STATUS_CODE_NOT_FOUND = 404
STATUS_CODE_METHOD_NOT_ALLOWED = 405

STATUS_CODE_INTERNAL_SERVER_ERROR = 500
STATUS_CODE_NOT_IMPLEMENTED = 501

UPTOBOX_TOKEN_LEN = 12

ALLOWED_CORS_DOMAINS = [
    'https://mon.astrocenter.fr',
]
